version: "3.7"
services:
  currency-exchange:
    image: vladjik00raskladjik/currency-exchange:0.0.1-RELEASE
    ports:
      - "3000:3000"
    restart: always
    networks:
      - currency-compose-network

  currency-conversion:
    image: vladjik00raskladjik/currency-conversion:0.0.1-RELEASE
    ports:
      - "3100:3100"
    restart: always
    environment:
      CURRENCY_EXCHANGE_SERVICE_HOST: http://currency-exchange:3000
    depends_on:
      - currency-exchange
    networks:
      - currency-compose-network

# Networks to be created to facilitate communication between containers
networks:
  currency-compose-network:
