apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  # How many pods in deployment
  replicas: 2
  minReadySeconds: 30
  selector:
    matchLabels:
      # Map deployment with pods by this label
      app: currency-conversion
  # Update strategy
  strategy:
    rollingUpdate:
      # How many instances can be created at time
      maxSurge: 25%
      # How many instances can be killed at time
      maxUnavailable: 25%
    type: RollingUpdate
  # Pods definition
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
      - image: vladjik00raskladjik/currency-conversion:0.0.4-RELEASE
        imagePullPolicy: IfNotPresent
        name: currency-conversion
        env:
          - name: CURRENCY_EXCHANGE_SERVICE_HOST
            value: http//currency-exchange
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  ports:
  - port: 3100
    protocol: TCP
    targetPort: 3100
  # Map service with pods by this label
  selector:
    app: currency-conversion
  sessionAffinity: None
  type: LoadBalancer
