apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
spec:
  # How many pods in deployment
  replicas: 3
  selector:
    matchLabels:
      # Map deployment with pods by this label
      app: currency-exchange
  # Update strategy
  strategy:
    rollingUpdate:
      # How many instances can be created at time
      maxSurge: 25%
      # How many instances can be killed at time
      maxUnavailable: 25%
    type: RollingUpdate
  # Pods definition
  template:
    metadata:
      labels:
        app: currency-exchange
    spec:
      containers:
      - image: vladjik00raskladjik/currency-exchange:0.0.3-RELEASE
        imagePullPolicy: IfNotPresent
        name: currency-exchange
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
spec:
  ports:
  - nodePort: 30029
    port: 3000
    protocol: TCP
    targetPort: 3000
  # Map service with pods by this label
  selector:
    app: currency-exchange
  sessionAffinity: None
  type: LoadBalancer
